### ISSUE TITLE
Customize front end website

### ISSUE THREAD

**Issue by TheBestSambo177** [TheBestSambo177/Business-Application-Programming#5]
Once the functionality is complete, we can begin creating and styling the part of the application that the user will be interacting with. This includes a navigation bar so that users can switch between pages depending on which feature they require. This task will be split between the two of us, with us each working on different pages while sharing insights and opinions on each other's work.

**Comment by JavarnTr** [comment]
Since I needed to begin testing my code in WordPress, I needed a functioning WordPress instance that I could use to implement shortcodes. We already had a WordPress instance on GitHub, but layout-wise it wasn't very suitable for this application. For testing purposes, the theme "Astra" was chosen for its simplicity. I plan to alter this design in the future once functionality is complete.

**Comment by JavarnTr** [comment]
I've implemented some basic design to make the website appear a little more user friendly. I've set the logo and icon, added some additional styling, and provided a short description/welcome on the homepage. I still need to style the properties page so that it looks a little nicer, but for now it's functional. I also want to add some images of New Zealand's landscape, but I'll have to find some landscape images that are free for public use as images have not been provided by the client.
![image](https://github.com/TheBestSambo177/Business-Application-Programming/assets/83565578/1587de82-9d3a-44f5-bba9-1dc4a6a66233)

**Comment by JavarnTr** [comment]
I've redesigned the layout of the properties page. The placeholder layout I made for testing purposes features small boxes that were all different sizes depending on how long the address was. Now I've followed a kind of table format, where each property is listed in a row that's divided into three types of information. The first box on the left is an image of the property, which at the current moment just features placeholder images. The second box has both the address and city in it. The third and final has a button to expand the listing on another page. I'm much happier with this design than the previous one, but I still want to implement a search bar at the top of the page. I do think that the page could use a bit more colour, which I'm hoping will be solved once I've found some decorative images to feature on the website. Maybe it could be displayed in the header or sidebars.

![image](https://github.com/TheBestSambo177/Business-Application-Programming/assets/83565578/8c8ecc15-f074-4be8-a23e-35f8f539300a)

**Comment by JavarnTr** [comment]
I've implemented a similar design for the booking page, giving details for the booking such as dates. 
![image](https://github.com/TheBestSambo177/Business-Application-Programming/assets/83565578/b4b9e084-b82c-4152-870f-ee6d34544372)

**Comment by JavarnTr** [comment]
The pages that didn't get a proper makeover are still functional in terms of the elements that have been applied to them. This includes the accounts page, booking, and checkout. Other than that I'm happy with the designs that I went with for home, properties, and booking display.
